### ISSUE TITLE
Using cloudmesh-common

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/yamldb#3]
I know that this doesn't really belong here, (but I have no idea where to place this, I've not used CloudMesh before)..

when I'm trying to run the tests, this is my output.. (caught when installing CloudMesh)

Collecting cloudmesh
  Downloading cloudmesh-2.3.2.zip (472 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 472.8/472.8 kB 3.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-oo9hnj0y/cloudmesh_8b1e1281a7fb45739358d43ab2ae782f/setup.py", line 44
          print "Install Test"
          ^^^^^^^^^^^^^^^^^^^^
      SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

_Originally posted by @voryzen in https://github.com/cloudmesh/yamldb/issues/2#issuecomment-1296450149_

**Comment by laszewsk** [comment]
You are running an old version of cloudmesh. We have split it up in multiple packages which are much easier to handle

I suggest you do 

pip install -r requirements-dev.txt

I also added documentation in the README

**Comment by laszewsk** [comment]
this has been fixed with switchin gto pyproject.toml
